# Test values for PostgreSQL migration
decisionEngine:
  useMySQL: false
  usePostgreSQL: true
  useRedis: true

postgresql:
  enabled: true
  auth:
    username: "db_user"
    password: "db_pass"
    database: "decision_engine_db"

# Configure database migration
dbMigration:
  enabled: true
  postgresql:
    enabled: true
    # This is a minimal example migration that creates a test table
    initSqlScript: |
      -- Example migration script for PostgreSQL
      DROP TABLE IF EXISTS test_table;
      CREATE TABLE test_table (
        id SERIAL PRIMARY KEY,
        name VARCHAR(255) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
