[log.console]
enabled = true
level = "DEBUG"
log_format = "default"

[server]
host = "0.0.0.0"
port = 8080

[limit]
request_count = 1
duration = 60

[database]
username = "root"
password = "root"
host = "host.docker.internal"
port = 3306
dbname = "jdb"

[redis]
host = "host.docker.internal"
port = 6379
pool_size = 5
reconnect_max_attempts = 5
reconnect_delay = 5
use_legacy_version = false
stream_read_count = 1
auto_pipeline = true
disable_auto_backpressure = false
max_in_flight_commands = 5000
default_command_timeout = 30
unresponsive_timeout = 10
max_feed_count = 200

[cache]
tti = 7200 # i.e. 2 hours
max_capacity = 5000

[secrets]
open_router_private_key = ""

[tenant_secrets]
public = { master_key = "", public_key = "", schema = "public" }

[secrets_management]
secrets_manager = "no_encryption"

[secrets_management.aws_kms]
key_id = "us-west-2"
region = "abc"

[api_client]
client_idle_timeout = 90
pool_max_idle_per_host = 10
identity = ""

